
- name: Configure Netsentry nftables firewall 
  hosts: localhost 
  connection: local 
  become: true 

  vars_files:
    - ../config/vars.yml
  
  tasks: 
    - name: install nftables
      ansible.builtin.apt:
        name: nftables
        state: present 
        update_cache: true

    - name: enable ipv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_file: /etc/sysctl.d/99-netsentry.conf
    
    - name: install nftables configuration file
      ansible.builtin.template:
        src: ../templates/firewall.nft.j2
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: '0644'
        validate: "/usr/sbin/nft --check --file %s"
      notify: Reload nftables
    - name: enable and start nftables service 
      ansible.builtin.systemd_service:
        name: nftables
        enabled: true
        state: started
  handlers:
    - name: Reload nftables
      ansible.builtin.systemd:
        name: nftables
        state: reloaded